### ISSUE TITLE
how to put the dufs page with Login information into iframe by URL

### ISSUE THREAD

**Issue by hjx620** [sigoden/dufs#370]
## Specific Demand
put the page into iframe without Login

my dufs ip is http://192.168.5.67:32381. I want to embed the dufs page into another page without login.

I have url,which is http://admin:admin@192.168.5.67:32381. But the url with username and password is not identified by iframe. I must login with enter ing my username and password by my hand. I want to put 
username and password in the url，which can be identified by iframe.what should i do?
thank you.

**Comment by hjx620** [comment]
how can i put the username and password into the URL effectively？

![mmexport1710901107600](https://github.com/sigoden/dufs/assets/73241960/49776170-2a63-4916-bd3e-2420a002f41c)

**Comment by sigoden** [comment]
All basic auth related behaviors are controlled by the browser. There's nothing dufs can do.

It is not safe to expose username and password on the front end.

Instead of setting the username and password and having it show up in the url, why not set read-only permissions on the directory via the auth control.
