### ISSUE TITLE
Ignore flag "commonName"

### ISSUE THREAD

**Issue by bropines** [sigoden/dufs#388]
When I tried to configure everything, I received an error in response to the self-signed certificate
`Server certificate was missing commonName attribute in subject name`. As GPT explained to me, I need to register the servers from which I connect (or to which I connect) (as I understand). And as a result, it somehow crookedly does not work for me through port querying. Is it possible to disable the CN check with a flag or not (so that I can log in from any Internet)?

**Comment by sigoden** [comment]
dufs handles self-signed certificates just fine.
If you encounter this error, it is highly likely that it's due to issues with the self-signed certificate you generated yourself.

The directory below contains the self-signed certificate and its generation script used for the dufs tests, which you can also refer to.
https://github.com/sigoden/dufs/tree/main/tests/data
