### ISSUE TITLE
Why use [ dufs -a "@/:rw" ] in webdav fail? it's shows unauth when i try use no username and passwd

### ISSUE THREAD

**Issue by zhi2xin1** [sigoden/dufs#450]
**Problem**

Why use [ dufs -a "@/:rw" ] in webdav fail? it's shows unauth when i try use no username and passwd

The client is AIMP play run in my android phone.
When I use admin:admin to login it works(this time with -a admin:admin) 

**Configuration**

use with no config file

**Log**

 .\dufs.exe -a  "@/:rw"
Listening on:
  http://127.0.0.1:5000/
  http://192.168.2.16:5000/
  http://[::1]:5000/

2024-09-06T23:51:47+08:00 INFO - 192.168.2.9 "PROPFIND /" 401
2024-09-06T23:51:48+08:00 INFO - 192.168.2.9 "PROPFIND /" 401

**Screenshots/Media**

**Environment Information**
 - Dufs version: 0.42.0
 - Browser/Webdav info: webdav
 - OS info: windows 
 - Proxy server (if any):   no proxy

**Comment by sigoden** [comment]
`dufs -a @/:rw` is misconfig, use `dufs -A` instead.

**Comment by zhi2xin1** [comment]
May be you missunderstand my mean, I try to set user not set -A, the problem is that I can't login with out username and passwd

**Comment by zhi2xin1** [comment]
> `dufs -a @/:rw` is misconfig, use `dufs -A` instead.
> 
> And I cannot confirm the 401 problem.

May be you missunderstand my mean, I try to use -a to set  user not set -A to set file auth, and the problem is that I can't login with out username and passwd

**Comment by sigoden** [comment]
@zhi2xin1 

You have two problems:

### Misconfiguration

If you want everyone to be able to access every file with read and write permissions, you should run `dufs -A`. If you want everyone to have read-only access to all files, you should run `dufs`.

Dufs uses `--allow-*` to permit operations. If you do not allow write operations such as `--allow-upload` or `--allow-delete`, setting the auth to `@/:rw` is meaningless.

### Cannot reproduce

Even when we run `dufs -a @/:rw`, everything is fine; we cannot reproduce the 401 error that your logs indicate.


## Final

Please provide more detailed information for reproducing, including configuration, execution commands, and screenshots (on webdav client). Otherwise, we won't be able to assist you.
